# Generated by Django 5.2.13 on 2026-05-07 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('id_number', models.CharField(max_length=300)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('date_range', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('pay_cycle', models.IntegerField()),
                ('rate', models.FloatField()),
                ('earnings_allowance', models.FloatField(default=0)),
                ('deductions_tax', models.FloatField(default=0)),
                ('deductions_health', models.FloatField(default=0)),
                ('pag_ibig', models.FloatField(default=0)),
                ('sss', models.FloatField(default=0)),
                ('overtime', models.FloatField(default=0)),
                ('total_pay', models.FloatField()),
                ('id_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='shemuapp.employee')),
            ],
        ),
    ]
